create_records([
    {
      name: 'Test Order',
      firstname: 'Test',
      lastname: 'Tlast',
      email: 'test@test.com',
      twitter: '@test',
      in_hand_by: '1/2/1015',
      terms: 'Half down on purchase',
      tax_exempt: false,
      sales_status: 'Pending',
      delivery_method: 'Ship to one location',
      phone_number: '123-456-8456',
      store_id: 1,
      salesperson_id: 1
    },
    {
      name: 'Other Order',
      firstname: 'Who',
      lastname: 'Cares',
      email: 'cooler@test.com',
      twitter: '@someone',
      in_hand_by: '4/2/2015',
      terms: 'Half down on purchase',
      tax_exempt: false,
      redo_reason: 'Because why not',
      sales_status: 'Pending',
      delivery_method: 'Ship to multiple locations',
      phone_number: '321-888-5448',
      store_id: 1,
      salesperson_id: 1
    },
    {
      name: 'Need More Orders',
      firstname: 'Number',
      lastname: 'One',
      email: 'aaa@example.com',
      twitter: '@tttttttt',
      in_hand_by: '1/5/7776',
      terms: 'Paid in full on purchase',
      tax_exempt: false,
      sales_status: 'Cancelled',
      delivery_method: 'Pick up in Ann Arbor',
      phone_number: '987-654-3214',
      store_id: 1,
      salesperson_id: 1
    },
    {
      name: 'Order Extreme!!!',
      firstname: 'INSANE',
      lastname: 'WHOA',
      email: 'idontknow@example.com',
      twitter: '@hmmm',
      in_hand_by: '2/2/2020',
      terms: 'Half down on purchase',
      tax_exempt: false,
      sales_status: 'Paid',
      delivery_method: 'Pick up in Ypsilanti',
      phone_number: '390-333-2222',
      store_id: 1,
      salesperson_id: 1
    },
    {
      name: "What's going on here",
      firstname: 'Need',
      lastname: 'TheseOrders',
      email: 'makingmoreorders@me.com',
      twitter: '@whaaaatever',
      in_hand_by: '2/6/7444',
      terms: 'Half down on purchase',
      tax_exempt: false,
      sales_status: 'Pending',
      delivery_method: 'Ship to one location',
      phone_number: '343-333-3333',
      store_id: 1,
      salesperson_id: 2
    },
    {
      name: 'CANT WAIT',
      firstname: 'TO',
      lastname: 'SEARCHTHESE',
      email: 'Thistakesawhile@waefhjaf.com',
      twitter: '@dddd',
      in_hand_by: '1/2/1015',
      terms: 'Half down on purchase',
      tax_exempt: false,
      sales_status: 'Pending',
      delivery_method: 'Ship to one location',
      phone_number: '123-456-8456',
      store_id: 1,
      salesperson_id: 2
    }
  ], Order)